#!/bin/bash
supervisorctl stop all
cd /srv/skynet-app/
virtualenv env
/srv/skynet-app/env/bin/python -m pip install -r requirements.txt
cd /srv/skynet-app/www/
rm -rf node_modules
npm cache clean
npm install
npm run-script build
if [ "$DEPLOYMENT_GROUP_NAME" == "skynet-app-stg" ]; then
    cp /srv/skynet-app/config/cfg.stg.py /srv/skynet-app/config/cfg.py
elif [ "$DEPLOYMENT_GROUP_NAME" == "skynet-app-prd" ]; then
    cp /srv/skynet-app/config/cfg.prd.py /srv/skynet-app/config/cfg.py
fi
find /srv/skynet-app/ -name "*.pyc" -type f -delete
/srv/skynet-app/env/bin/python -m compileall /srv/skynet-app/
supervisorctl restart all
